name: Label validation

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  # Note: Unique name used in list of required status checks for the 'main' branch protection rule
  label-semver:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Validate presence of exactly one SemVer2 label
        uses: mheap/github-action-required-labels@8afbe8ae6ab7647d0c9f0cfa7c2f939650d22509 #v5.5.1
        with:
          mode: exactly
          count: 1
          labels: "patch, minor, major"
          add_comment: true
